### PR TITLE
added 8.20.5 version

### PR DESCRIPTION
**Pull request by Pyroseza**

### CODE REVIEW

**Comment by clouless** [comment]
Thanks for your contribution. I habe a script to create new versions and have just provided 8.20.5.

https://github.com/codeclou/docker-atlassian-jira-data-center/tree/master/versions/8.20.5

**Comment by Pyroseza** [comment]
Hi @clouless, it's more than just a new version, I've updated postgresql to 12.9 and make use of a named volume, and tested on newer macos and bash versions

**Comment by clouless** [comment]
Hi @Pyroseza ok thanks a lot. I will look deeper into it, thanks :)

**Comment by clouless** [comment]
Let me resolve the conflicts, as part of review, thanks 👍

**Comment by Pyroseza** [comment]
no problem, let me know if anything doesn't make sense or if you want me to change anything, happy to contribute to a great repo like this 😄

**Review by clouless — APPROVED** [review]
awesome 🎉 🥇

**Comment by Pyroseza** [comment]
woohoo 🥳

**Comment by clouless** [comment]
@Pyroseza thanks a lot, I will try to update the versions more regularly from now on 😓  ... I thought only I would use it internally ^^

**Comment by clouless** [comment]
I credited you in the main README if that is ok for you :) https://github.com/codeclou/docker-atlassian-jira-data-center/commit/2e86db3a15846438f48bc4ef3e7f4fef24fae1fa

**Comment by Pyroseza** [comment]
you're most welcome 👍 
I'm going to be quite active within the DC support department, so I will gladly help you 😄 

awesome thank you so much! 🙌

**Pull request merged**
